### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ratseater** [davidsvy/color-stealing#1]
Traceback (most recent call last):
  File "/home/navaja/progs/color-stealing/run.py", line 90, in <module>
    main()
  File "/home/navaja/progs/color-stealing/run.py", line 85, in main
    canvas, ifs = build_fractal(args)
  File "/home/navaja/progs/color-stealing/src/chaos_game.py", line 234, in build_fractal
    fractal = color_steal(args)
  File "/home/navaja/progs/color-stealing/src/chaos_game.py", line 138, in color_steal
    min_fractal, max_fractal = find_min_max(buffer_fractal)
  File "/home/navaja/progs/color-stealing/src/chaos_game.py", line 26, in find_min_max
    min_, max_ = point_list[0][0]
IndexError: list index out of range

**Comment by ratseater** [comment]
python run.py -s -i 100 -nt -l templates/ifs/10.csv -c templates/images/11.png

**Comment by davidsvy** [comment]
The reason for this error is the number of iterations you specify (the argument `-i 100`). By default the first 200 iterations are skipped for convergence reasons (this can be changed with the `-ni` argument). A simple fix is to increase the number of iterations. \
\
Additionally, the `-c` argument should be the path of some vibrant image (like those in the `assets/auxiliary ` directory.\
\
All things considered, try running:\
`python run.py -s -i 100000 -nt -l templates/ifs/10.csv -c assets/auxiliary/lava.jpg`
